CREATE TABLE IF NOT EXISTS artists (
  artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  artist_name varchar NOT NULL UNIQUE,
  birthday DATE NOT NULL,
  birthplace varchar NOT NULL,
  is_alive BOOLEAN NOT NULL DEFAULT 'true'
);